In [1]:
import  time 
import numpy as np
print(np.__version__)

1.22.4


In [45]:
for i in range(0,10,3):
    print(i)

for i in range(-1,-5,-1):
    print(i)

0
3
6
9
-1
-2
-3
-4


In [49]:
fruits = ['apple', 'banana', 'cherry']

for index, fruit in enumerate(fruits, start=1):
    print(f"Index {index}: {fruit}")

names = ['Alice', 'Bob', 'Charlie']
scores = [85, 90, 78]
ages = [25, 30, 22]

for name, score, age in zip(names, scores, ages):
    print(f"{name}, age {age}, scored {score}")



Index 1: apple
Index 2: banana
Index 3: cherry
Alice, age 25, scored 85
Bob, age 30, scored 90
Charlie, age 22, scored 78


# satu

In [2]:
hasil= []
waktu= time.time()
for x in range(1, 10**6):
    hasil.append(x+3)
print("sekon:", time.time()-waktu)

sekon: 0.1265113353729248


In [3]:
waktu= time.time()
hasil= [x+3 for x in range(1, 10**6)]
print("sekon:", time.time()-waktu)

sekon: 0.07160592079162598


In [4]:
waktu = time.time()
hasil = np.arange(start=1, stop=10**6) + 3
print("sekon:", time.time() - waktu)

sekon: 0.01488494873046875


# dua

In [5]:
waktu = time.time()
np.random.seed(0)
awal= np.random.randint(low=1, high=10, size=(10**6))
hasil= np.sum(awal)
print(hasil)
print("sekon:", time.time() - waktu)

5001524
sekon: 0.016614675521850586


In [6]:
waktu = time.time()
np.random.seed(0)
awal= np.random.randint(low=1, high=10, size=(10**6))
hasil= sum(awal)
print(hasil)
print("sekon:", time.time() - waktu)

5001524
sekon: 0.06989359855651855


In [7]:
waktu = time.time()
np.random.seed(0)
test= np.random.randint(low=1, high=10, size=(10**6))
kosong=0
for i in test:
    kosong += i
print(kosong)
print("sekon:", time.time() - waktu)

5001524
sekon: 0.12168574333190918


# tiga

In [8]:
import numpy as np

# Create two 2x2 matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print(matrix1)
print(matrix2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [9]:
# Calculate the dot product
dot_product = np.dot(matrix1, matrix2)
print("dot product")
print(dot_product)

matmul_mat = np.matmul(matrix1, matrix2)
print("matmul_mat")
print(matmul_mat)

scalar_mul= np.multiply(matrix1, matrix2)
print("scalar_mul")
print(scalar_mul)

dot product
[[19 22]
 [43 50]]
matmul_mat
[[19 22]
 [43 50]]
scalar_mul
[[ 5 12]
 [21 32]]


In [10]:
stack_matrix= np.stack((matrix1, matrix2), axis=1)
print(stack_matrix.shape)
print(stack_matrix)
print("\nreshape: ")
print(stack_matrix.reshape(-1,2))

(2, 2, 2)
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]

reshape: 
[[1 2]
 [5 6]
 [3 4]
 [7 8]]


In [11]:
vstack_matrix= np.vstack((matrix1, matrix2))
print(vstack_matrix.shape)
print(vstack_matrix)

(4, 2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [12]:
conc_matrix= np.concatenate((matrix1, matrix2), axis=0)
print(conc_matrix.shape)
print(conc_matrix)

(4, 2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# empat

In [13]:
a= np.array([-2, -1, 0, 1, 2, 3])
hasil= np.where(a>0, a, 
         np.where(a<0, a*10, 999))
print(hasil)

[-20 -10 999   1   2   3]


In [14]:
hasil=[]
for i in a:
    print(i)
    if i>0:
        hasil.append(i)
    elif i<0:
        hasil.append(i*10)
    else:    
        hasil.append(999)
print(hasil)

-2
-1
0
1
2
3
[-20, -10, 999, 1, 2, 3]


In [15]:
hasil = [i if i > 0 else i*10 if i < 0 else 999 for i in a]
print(hasil)

[-20, -10, 999, 1, 2, 3]


# lima

In [35]:
np.random.seed(0)
a= np.random.randint(low=1, high=10, size=(2,4))
a

array([[6, 1, 4, 4],
       [8, 4, 6, 3]])

In [36]:
print(a[0][1])
print(a[0,1])

1
1


In [47]:
print(a[1,:])
print(a[0, :2])
print(a[:][:])

[8 4 6 3]
[6 1]
[[6 1 4 4]
 [8 4 6 3]]
